/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void init_systick_timer(uint32_t tick_hz);

#define TASK_STACK_SIZE 		1024U
#define SCHED_STACK_SIZE		1024U

#define SRAM_START				0x20000000U
#define SRAM_SIZE				((128) * (1024))
#define SRAM_END				(SRAM_START + SRAM_SIZE)

#define TASK_1_STACK_START		(SRAM_END)
#define TASK_2_STACK_START		(SRAM_END) - (1 * (TASK_STACK_SIZE))
#define TASK_3_STACK_START		(SRAM_END) - (2 * (TASK_STACK_SIZE))
#define TASK_4_STACK_START		(SRAM_END) - (3 * (TASK_STACK_SIZE))
#define SCHED_STACK_START		(SRAM_END) - (4 * (TASK_STACK_SIZE))
#define TICK_HZ					1000U

#define HSI_CLOCK				1600000U
#define SYSTICK_TIM_CLK			HSI_CLOCK

int main(void)
{
	init_systick_timer(TICK_HZ);
    /* Loop forever */
	for(;;);
}


void task1_handler(void) {

	for(;;){

		printf("This is Task1\n");
	}
}

void task2_handler(void) {

	for(;;){

		printf("This is Task2\n");
	}
}

void task3_handler(void) {

	for(;;){

		printf("This is Task3\n");
	}
}

void task4_handler(void) {

	for(;;){

		printf("This is Task4\n");
	}
}


void init_systick_timer(uint32_t tick_hz) {

	// accessing the systic registers
	uint32_t * pSYST_RVR = (uint32_t *)0xE000E014;
	uint32_t * pSYST_CSR = (uint32_t *)0xE000E010;

	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;


	// clear the value of SVR
	*pSYST_RVR &= ~(0x00FFFFFFFF);

	// load the value into the SVR register
	*(pSYST_RVR) |= count_value;

	// Set the clock to the system timer from the processor clock
	*pSYST_CSR |= (1 << 2);
	// Enable exception setting TICKINT  so that exception handler is called
	*pSYST_CSR |= (1 << 1);
	// Enable the counter
	*pSYST_CSR |= (1 << 0);
}


void SysTick_Handler(void) {


}
