/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);


#define TASK_STACK_SIZE 		1024U
#define SCHED_STACK_SIZE		1024U

#define SRAM_START				0x20000000U
#define SRAM_SIZE				((128) * (1024))
#define SRAM_END				(SRAM_START + SRAM_SIZE)

#define TASK_1_STACK_START		(SRAM_END)
#define TASK_2_STACK_START		(SRAM_END) - (1 * (TASK_STACK_SIZE))
#define TASK_3_STACK_START		(SRAM_END) - (2 * (TASK_STACK_SIZE))
#define TASK_4_STACK_START		(SRAM_END) - (3 * (TASK_STACK_SIZE))
#define SCHED_STACK_START		(SRAM_END) - (4 * (TASK_STACK_SIZE))


int main(void)
{
    /* Loop forever */
	for(;;);
}


void task1_handler(void) {

	for(;;){

		printf("This is Task1\n");
	}
}

void task2_handler(void) {

	for(;;){

		printf("This is Task2\n");
	}
}

void task3_handler(void) {

	for(;;){

		printf("This is Task3\n");
	}
}

void task4_handler(void) {

	for(;;){

		printf("This is Task4\n");
	}
}
